// npx ctx-pilot export - Generate static context files

import { readFile, writeFile, mkdir } from 'fs/promises';
import { join, dirname } from 'path';
import { configExists, loadConfig } from '../config/index.js';
import { loadIndex, getIndexStats } from '../indexer/index.js';
import type { CommandContext, ExportTarget } from './types.js';
import type { CtxPilotConfig, ProjectIndex } from '../types.js';

export interface ExportConfig {
  name: string;
  outputPath: string;
  maxChars?: number;
  format: (config: CtxPilotConfig, index: ProjectIndex, projectRoot: string) => Promise<string>;
}

// Format pinned files content for static exports
async function formatPinnedContent(config: CtxPilotConfig, projectRoot: string, maxChars?: number): Promise<string> {
  const sections: string[] = [];
  let totalChars = 0;

  for (const pinnedPath of config.pinned) {
    try {
      const absolutePath = join(projectRoot, pinnedPath);
      let content = await readFile(absolutePath, 'utf-8');

      // Truncate if needed
      if (maxChars && totalChars + content.length > maxChars) {
        const remaining = maxChars - totalChars - 100; // Leave room for header
        if (remaining > 200) {
          content = content.slice(0, remaining) + '\n\n... (truncated)';
        } else {
          break;
        }
      }

      sections.push(`## ${pinnedPath}\n\n${content}`);
      totalChars += content.length;

      if (maxChars && totalChars >= maxChars) break;
    } catch {
      // Skip missing files
    }
  }

  return sections.join('\n\n---\n\n');
}

// Format index summary for static exports
function formatIndexSummary(index: ProjectIndex): string {
  const lines: string[] = ['## Codebase Structure\n'];

  for (const file of index.files.slice(0, 50)) { // Limit to 50 files
    lines.push(`### ${file.path}`);
    for (const section of file.sections.slice(0, 10)) { // Limit sections per file
      lines.push(`- ${section.title} (lines ${section.lineStart}-${section.lineEnd})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export const EXPORT_CONFIGS: Record<ExportTarget, ExportConfig> = {
  cursor: {
    name: 'Cursor',
    outputPath: '.cursorrules',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --cursor

${pinned}

---

${summary}
`;
    },
  },
  windsurf: {
    name: 'Windsurf',
    outputPath: '.windsurfrules',
    maxChars: 6000,
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot, 4000);
      const stats = getIndexStats(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --windsurf

${pinned}

---

## Project Stats
- Indexed files: ${stats.files}
- Indexed sections: ${stats.sections}
- Pinned files: ${config.pinned.join(', ') || 'none'}
`;
    },
  },
  aider: {
    name: 'Aider',
    outputPath: '.aider.context.md',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context for Aider
# Use with: aider --read .aider.context.md
# Regenerate with: npx ctx-pilot export --aider

${pinned}

---

${summary}
`;
    },
  },
  mdc: {
    name: 'Cursor MDC',
    outputPath: '.cursor/rules/ctx-pilot.mdc',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);

      return `---
description: Project context from ctx-pilot
globs: ["**/*"]
alwaysApply: true
---

# Project Context

${pinned}

## Key Files

${config.pinned.map(f => `- ${f}`).join('\n')}
`;
    },
  },
};

export function parseExportTargets(args: string[]): ExportTarget[] {
  const targets: ExportTarget[] = [];
  if (args.includes('--cursor')) targets.push('cursor');
  if (args.includes('--windsurf')) targets.push('windsurf');
  if (args.includes('--aider')) targets.push('aider');
  if (args.includes('--mdc')) targets.push('mdc');
  if (args.includes('--all')) {
    return ['cursor', 'windsurf', 'aider', 'mdc'];
  }
  return targets;
}

export async function runExport(ctx: CommandContext): Promise<void> {
  const { projectRoot, args } = ctx;
  const targets = parseExportTargets(args);

  if (targets.length === 0) {
    console.error('Specify export target: --cursor, --windsurf, --aider, --mdc, or --all');
    process.exit(1);
  }

  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);
  if (!index) {
    console.error('No index found. Ask your AI to: "Follow the instructions in .context/optimize.md"');
    process.exit(1);
  }

  for (const target of targets) {
    const exportConfig = EXPORT_CONFIGS[target];
    const outputPath = join(projectRoot, exportConfig.outputPath);

    // Ensure directory exists for MDC
    await mkdir(dirname(outputPath), { recursive: true });

    const content = await exportConfig.format(config, index, projectRoot);
    await writeFile(outputPath, content, 'utf-8');

    console.log(`Exported to ${exportConfig.outputPath} for ${exportConfig.name}`);
  }
}
