#!/usr/bin/env node

import { readFile, writeFile, mkdir, access } from 'fs/promises';
import { join, dirname } from 'path';
import { watch } from 'chokidar';
import { loadConfig, configExists, saveConfig, getDefaultConfig, getContextDir } from './config/index.js';
import { loadIndex, buildIndex, getIndexStats } from './indexer/index.js';
import { searchSections } from './search/index.js';
import { extractTopics } from './search/keywords.js';
import type { HookInput, ScoredSection, CtxPilotConfig, ProjectIndex } from './types.js';

// Supported AI CLI environments (dynamic hooks)
type Environment = 'claude' | 'gemini' | 'unknown';

// Supported export targets (static files)
type ExportTarget = 'cursor' | 'windsurf' | 'aider' | 'mdc';

interface EnvironmentConfig {
  name: string;
  settingsDir: string;
  settingsFile: string;
  hookEvent: string;
  restartMessage: string;
}

interface ExportConfig {
  name: string;
  outputPath: string;
  maxChars?: number;
  format: (config: CtxPilotConfig, index: ProjectIndex, projectRoot: string) => Promise<string>;
}

const ENVIRONMENTS: Record<Exclude<Environment, 'unknown'>, EnvironmentConfig> = {
  claude: {
    name: 'Claude Code',
    settingsDir: '.claude',
    settingsFile: 'settings.json',
    hookEvent: 'UserPromptSubmit',
    restartMessage: 'Restart Claude Code to activate the hook.',
  },
  gemini: {
    name: 'Gemini CLI',
    settingsDir: '.gemini',
    settingsFile: 'settings.json',
    hookEvent: 'BeforeAgent',
    restartMessage: 'Restart Gemini CLI to activate the hook.',
  },
};

// Format pinned files content for static exports
async function formatPinnedContent(config: CtxPilotConfig, projectRoot: string, maxChars?: number): Promise<string> {
  const sections: string[] = [];
  let totalChars = 0;

  for (const pinnedPath of config.pinned) {
    try {
      const absolutePath = join(projectRoot, pinnedPath);
      let content = await readFile(absolutePath, 'utf-8');

      // Truncate if needed
      if (maxChars && totalChars + content.length > maxChars) {
        const remaining = maxChars - totalChars - 100; // Leave room for header
        if (remaining > 200) {
          content = content.slice(0, remaining) + '\n\n... (truncated)';
        } else {
          break;
        }
      }

      sections.push(`## ${pinnedPath}\n\n${content}`);
      totalChars += content.length;

      if (maxChars && totalChars >= maxChars) break;
    } catch {
      // Skip missing files
    }
  }

  return sections.join('\n\n---\n\n');
}

// Format index summary for static exports
function formatIndexSummary(index: ProjectIndex): string {
  const lines: string[] = ['## Codebase Structure\n'];

  for (const file of index.files.slice(0, 50)) { // Limit to 50 files
    lines.push(`### ${file.path}`);
    for (const section of file.sections.slice(0, 10)) { // Limit sections per file
      lines.push(`- ${section.title} (lines ${section.lineStart}-${section.lineEnd})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

const EXPORT_CONFIGS: Record<ExportTarget, ExportConfig> = {
  cursor: {
    name: 'Cursor',
    outputPath: '.cursorrules',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --cursor

${pinned}

---

${summary}
`;
    },
  },
  windsurf: {
    name: 'Windsurf',
    outputPath: '.windsurfrules',
    maxChars: 6000,
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot, 4000);
      const stats = getIndexStats(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --windsurf

${pinned}

---

## Project Stats
- Indexed files: ${stats.files}
- Indexed sections: ${stats.sections}
- Pinned files: ${config.pinned.join(', ') || 'none'}
`;
    },
  },
  aider: {
    name: 'Aider',
    outputPath: '.aider.context.md',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context for Aider
# Use with: aider --read .aider.context.md
# Regenerate with: npx ctx-pilot export --aider

${pinned}

---

${summary}
`;
    },
  },
  mdc: {
    name: 'Cursor MDC',
    outputPath: '.cursor/rules/ctx-pilot.mdc',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);

      return `---
description: Project context from ctx-pilot
globs: ["**/*"]
alwaysApply: true
---

# Project Context

${pinned}

## Key Files

${config.pinned.map(f => `- ${f}`).join('\n')}
`;
    },
  },
};

const SETUP_INSTRUCTIONS = `## ctx-pilot Setup Required

Create a config file at \`.context/config.json\`:

\`\`\`json
{
  "pinned": [],
  "include": ["**/*.md"],
  "exclude": [],
  "tokenBudget": 32000,
  "maxContextPercentage": 50
}
\`\`\`

Or run \`npx ctx-pilot init\` to create a default config.
`;

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf-8');
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function detectEnvironment(projectRoot: string): Promise<Environment> {
  const claudeExists = await pathExists(join(projectRoot, '.claude'));
  const geminiExists = await pathExists(join(projectRoot, '.gemini'));

  if (claudeExists && geminiExists) {
    const claudeSettings = await pathExists(join(projectRoot, '.claude', 'settings.json'));
    const geminiSettings = await pathExists(join(projectRoot, '.gemini', 'settings.json'));
    if (claudeSettings && !geminiSettings) return 'claude';
    if (geminiSettings && !claudeSettings) return 'gemini';
    return 'claude';
  }

  if (claudeExists) return 'claude';
  if (geminiExists) return 'gemini';

  if (process.env.CLAUDE_CODE || process.env.ANTHROPIC_API_KEY) return 'claude';
  if (process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY) return 'gemini';

  return 'claude';
}

async function installHook(projectRoot: string, forceEnv?: Environment): Promise<void> {
  const env = forceEnv || await detectEnvironment(projectRoot);

  if (env === 'unknown') {
    console.log('Could not detect AI CLI environment.');
    console.log('Use --claude or --gemini flag to specify.');
    return;
  }

  const config = ENVIRONMENTS[env];
  const settingsDir = join(projectRoot, config.settingsDir);
  const settingsPath = join(settingsDir, config.settingsFile);

  await mkdir(settingsDir, { recursive: true });

  let settings: Record<string, unknown> = {};
  try {
    const content = await readFile(settingsPath, 'utf-8');
    settings = JSON.parse(content);
  } catch {
    // File doesn't exist
  }

  if (!settings.hooks) settings.hooks = {};
  const hooks = settings.hooks as Record<string, unknown[]>;
  if (!hooks[config.hookEvent]) hooks[config.hookEvent] = [];

  const eventHooks = hooks[config.hookEvent] as Array<Record<string, unknown>>;
  const hasHook = eventHooks.some((h) => {
    const hHooks = h.hooks as Array<Record<string, unknown>> | undefined;
    return hHooks?.some((hh) => String(hh.command || '').includes('ctx-pilot'));
  });

  if (hasHook) {
    console.log(`Hook already installed for ${config.name}.`);
    return;
  }

  eventHooks.push({
    matcher: '',
    hooks: [{ type: 'command', command: 'npx ctx-pilot' }],
  });

  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
  console.log(`Hook installed for ${config.name} at ${config.settingsDir}/${config.settingsFile}`);
}

async function runExport(projectRoot: string, target: ExportTarget): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  let index = await loadIndex(projectRoot);
  if (!index) {
    console.log('Building index...');
    index = await buildIndex(projectRoot, config, { force: true });
  }

  const exportConfig = EXPORT_CONFIGS[target];
  const outputPath = join(projectRoot, exportConfig.outputPath);

  // Ensure directory exists for MDC
  await mkdir(dirname(outputPath), { recursive: true });

  const content = await exportConfig.format(config, index, projectRoot);
  await writeFile(outputPath, content, 'utf-8');

  console.log(`Exported to ${exportConfig.outputPath} for ${exportConfig.name}`);
}

async function runWatch(projectRoot: string, targets: ExportTarget[]): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const contextDir = getContextDir(projectRoot);

  console.log(`Watching for changes...`);
  console.log(`Targets: ${targets.map(t => EXPORT_CONFIGS[t].name).join(', ')}`);
  console.log(`Patterns: ${config.include.join(', ')}`);
  console.log('Press Ctrl+C to stop.\n');

  // Initial export
  for (const target of targets) {
    await runExport(projectRoot, target);
  }

  // Set up watcher
  const watcher = watch(config.include, {
    cwd: projectRoot,
    ignored: [
      ...config.exclude,
      '**/node_modules/**',
      '**/.git/**',
      '.context/**',
      '.cursor/**',
      '.cursorrules',
      '.windsurfrules',
      '.aider.context.md',
    ],
    ignoreInitial: true,
    persistent: true,
  });

  let debounceTimer: NodeJS.Timeout | null = null;

  const regenerate = async () => {
    console.log(`\n[${new Date().toLocaleTimeString()}] Change detected, regenerating...`);

    try {
      // Rebuild index
      const newIndex = await buildIndex(projectRoot, config, { force: true });
      const stats = getIndexStats(newIndex);
      console.log(`  Index: ${stats.files} files, ${stats.sections} sections`);

      // Re-export all targets
      for (const target of targets) {
        const exportConfig = EXPORT_CONFIGS[target];
        const outputPath = join(projectRoot, exportConfig.outputPath);
        await mkdir(dirname(outputPath), { recursive: true });
        const content = await exportConfig.format(config, newIndex, projectRoot);
        await writeFile(outputPath, content, 'utf-8');
        console.log(`  Updated ${exportConfig.outputPath}`);
      }
    } catch (error) {
      console.error('  Error:', error);
    }
  };

  watcher.on('all', (event, path) => {
    // Debounce rapid changes
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(regenerate, 500);
  });

  // Keep process alive
  process.on('SIGINT', () => {
    console.log('\nStopping watch...');
    watcher.close();
    process.exit(0);
  });
}

async function runInit(projectRoot: string, forceEnv?: Environment): Promise<void> {
  const env = forceEnv || await detectEnvironment(projectRoot);
  const envConfig = env !== 'unknown' ? ENVIRONMENTS[env] : null;

  if (await configExists(projectRoot)) {
    console.log('Already configured. See .context/config.json');
    return;
  }

  const config = getDefaultConfig();
  await saveConfig(projectRoot, config);
  console.log('Created .context/config.json with defaults:');
  console.log(JSON.stringify(config, null, 2));

  console.log('\nBuilding index...');
  const index = await buildIndex(projectRoot, config, { force: true });
  const stats = getIndexStats(index);
  console.log(`Indexed ${stats.files} files with ${stats.sections} sections.`);

  if (envConfig) {
    console.log(`\nDetected ${envConfig.name}. Installing hook...`);
    await installHook(projectRoot, env as Exclude<Environment, 'unknown'>);
    console.log(`\nSetup complete! ${envConfig.restartMessage}`);
  } else {
    console.log('\nCould not detect AI CLI environment.');
    console.log('Run `npx ctx-pilot hook --claude` or `npx ctx-pilot hook --gemini` to install.');
  }
}

async function runIndex(projectRoot: string, force: boolean): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  console.log('Building index...');
  const index = await buildIndex(projectRoot, config, { force });
  const stats = getIndexStats(index);
  console.log(`Indexed ${stats.files} files with ${stats.sections} sections.`);
}

async function runStatus(projectRoot: string): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.log('Status: Not configured');
    console.log('Run `npx ctx-pilot init` to set up.');
    return;
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);
  const env = await detectEnvironment(projectRoot);

  console.log('Status: Configured');
  console.log(`Environment: ${env !== 'unknown' ? ENVIRONMENTS[env].name : 'Unknown'}`);
  console.log(`\nConfig (.context/config.json):`);
  console.log(`  Pinned: ${config.pinned.length > 0 ? config.pinned.join(', ') : '(none)'}`);
  console.log(`  Include: ${config.include.join(', ')}`);
  console.log(`  Exclude: ${config.exclude.length > 0 ? config.exclude.join(', ') : '(none)'}`);

  if (index) {
    const stats = getIndexStats(index);
    console.log(`\nIndex (.context/index.json):`);
    console.log(`  Files: ${stats.files}`);
    console.log(`  Sections: ${stats.sections}`);
    console.log(`  Last updated: ${index.lastUpdated}`);
  } else {
    console.log(`\nIndex: Not built yet.`);
  }

  // Check hooks
  console.log(`\nHooks:`);
  for (const [, envConfig] of Object.entries(ENVIRONMENTS)) {
    const settingsPath = join(projectRoot, envConfig.settingsDir, envConfig.settingsFile);
    if (await pathExists(settingsPath)) {
      try {
        const content = await readFile(settingsPath, 'utf-8');
        const settings = JSON.parse(content);
        const hooks = settings.hooks?.[envConfig.hookEvent] || [];
        const hasHook = hooks.some((h: Record<string, unknown>) => {
          const hHooks = h.hooks as Array<Record<string, unknown>> | undefined;
          return hHooks?.some((hh) => String(hh.command || '').includes('ctx-pilot'));
        });
        console.log(`  ${envConfig.name}: ${hasHook ? 'Installed' : 'Not installed'}`);
      } catch {
        console.log(`  ${envConfig.name}: Error reading settings`);
      }
    }
  }

  // Check exports
  console.log(`\nExports:`);
  for (const [, exportConfig] of Object.entries(EXPORT_CONFIGS)) {
    const exists = await pathExists(join(projectRoot, exportConfig.outputPath));
    if (exists) {
      console.log(`  ${exportConfig.name}: ${exportConfig.outputPath}`);
    }
  }
}

function formatSuggestions(pinnedFiles: string[], results: ScoredSection[], maxSuggestions = 5): string {
  const lines: string[] = [];

  if (pinnedFiles.length > 0) {
    lines.push('**Pinned (always relevant):**');
    for (const file of pinnedFiles) {
      lines.push(`- ${file}`);
    }
    lines.push('');
  }

  if (results.length > 0) {
    lines.push('**Relevant to your task:**');
    const top = results.slice(0, maxSuggestions);
    for (const r of top) {
      const lineRange = `lines ${r.section.lineStart}-${r.section.lineEnd}`;
      lines.push(`- ${r.file} (${lineRange}) - ${r.section.title}`);
    }
  }

  return lines.join('\n');
}

async function runHook(): Promise<void> {
  const projectRoot = process.cwd();

  try {
    const input = await readStdin();
    if (!input.trim()) process.exit(0);

    let data: HookInput;
    try {
      data = JSON.parse(input);
    } catch {
      process.exit(0);
    }

    if (!(await configExists(projectRoot))) {
      console.log(SETUP_INSTRUCTIONS);
      process.exit(0);
    }

    const config = await loadConfig(projectRoot);
    let index = await loadIndex(projectRoot);
    if (!index) index = await buildIndex(projectRoot, config);

    const topics = extractTopics(data.prompt);
    const query = topics.join(' ');
    const results = query ? searchSections(index, query, { maxResults: 10 }) : [];
    const suggestions = formatSuggestions(config.pinned, results);

    if (suggestions) {
      console.log(`<ctx-pilot>
Look into these files for context:

${suggestions}
</ctx-pilot>`);
    }

    process.exit(0);
  } catch (error) {
    console.error('ctx-pilot error:', error);
    process.exit(0);
  }
}

function printHelp(): void {
  console.log(`ctx-pilot - Intelligent context management for AI coding assistants

Supported:
  Dynamic hooks: Claude Code, Gemini CLI
  Static exports: Cursor, Windsurf, Aider

Usage:
  npx ctx-pilot                Run as hook (reads from stdin)
  npx ctx-pilot init           Create config and install hook
  npx ctx-pilot index          Rebuild the index
  npx ctx-pilot status         Show config, index, and hook status

Hooks (dynamic, per-prompt):
  npx ctx-pilot hook           Install hook (auto-detects Claude/Gemini)
  npx ctx-pilot hook --claude  Install for Claude Code
  npx ctx-pilot hook --gemini  Install for Gemini CLI

Exports (static files):
  npx ctx-pilot export --cursor    Generate .cursorrules
  npx ctx-pilot export --windsurf  Generate .windsurfrules
  npx ctx-pilot export --aider     Generate .aider.context.md
  npx ctx-pilot export --mdc       Generate .cursor/rules/ctx-pilot.mdc

Watch (auto-regenerate on file changes):
  npx ctx-pilot watch --cursor     Watch and update .cursorrules
  npx ctx-pilot watch --windsurf   Watch and update .windsurfrules
  npx ctx-pilot watch --aider      Watch and update .aider.context.md
  npx ctx-pilot watch --all        Watch and update all exports

Config file: .context/config.json
Index file:  .context/index.json
`);
}

function parseEnvFlag(args: string[]): Environment | undefined {
  if (args.includes('--claude')) return 'claude';
  if (args.includes('--gemini')) return 'gemini';
  return undefined;
}

function parseExportTargets(args: string[]): ExportTarget[] {
  const targets: ExportTarget[] = [];
  if (args.includes('--cursor')) targets.push('cursor');
  if (args.includes('--windsurf')) targets.push('windsurf');
  if (args.includes('--aider')) targets.push('aider');
  if (args.includes('--mdc')) targets.push('mdc');
  if (args.includes('--all')) {
    return ['cursor', 'windsurf', 'aider', 'mdc'];
  }
  return targets;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const projectRoot = process.cwd();
  const forceEnv = parseEnvFlag(args);
  const exportTargets = parseExportTargets(args);

  switch (args[0]) {
    case 'init':
      await runInit(projectRoot, forceEnv);
      break;
    case 'index':
      await runIndex(projectRoot, args.includes('--force'));
      break;
    case 'status':
      await runStatus(projectRoot);
      break;
    case 'hook':
    case 'install':
    case 'install-hook':
      await installHook(projectRoot, forceEnv);
      break;
    case 'export':
      if (exportTargets.length === 0) {
        console.error('Specify export target: --cursor, --windsurf, --aider, --mdc, or --all');
        process.exit(1);
      }
      for (const target of exportTargets) {
        await runExport(projectRoot, target);
      }
      break;
    case 'watch':
      if (exportTargets.length === 0) {
        console.error('Specify watch target: --cursor, --windsurf, --aider, --mdc, or --all');
        process.exit(1);
      }
      await runWatch(projectRoot, exportTargets);
      break;
    case 'help':
    case '--help':
    case '-h':
      printHelp();
      break;
    default:
      await runHook();
  }
}

main().catch((error) => {
  console.error('Error:', error.message);
  process.exit(1);
});
