#!/usr/bin/env node

import { readFile, writeFile, mkdir, access, stat } from 'fs/promises';
import { watch } from 'fs';
import { join, dirname } from 'path';
import { loadConfig, configExists, saveConfig, getDefaultConfig } from './config/index.js';
import { loadIndex, getIndexStats, buildAutoIndex, saveIndex } from './indexer/index.js';
import { searchSections } from './search/index.js';
import { extractTopics, setDomainStopwords } from './search/keywords.js';
import { validateIndex, formatValidationResult } from './validation/index.js';
import type { HookInput, ScoredSection, CtxPilotConfig, ProjectIndex } from './types.js';

// Supported AI CLI environments (dynamic hooks)
type Environment = 'claude' | 'gemini' | 'unknown';

// Supported export targets (static files)
type ExportTarget = 'cursor' | 'windsurf' | 'aider' | 'mdc';

interface EnvironmentConfig {
  name: string;
  settingsDir: string;
  settingsFile: string;
  hookEvent: string;
  restartMessage: string;
}

interface ExportConfig {
  name: string;
  outputPath: string;
  maxChars?: number;
  format: (config: CtxPilotConfig, index: ProjectIndex, projectRoot: string) => Promise<string>;
}

const ENVIRONMENTS: Record<Exclude<Environment, 'unknown'>, EnvironmentConfig> = {
  claude: {
    name: 'Claude Code',
    settingsDir: '.claude',
    settingsFile: 'settings.json',
    hookEvent: 'UserPromptSubmit',
    restartMessage: 'Restart Claude Code to activate the hook.',
  },
  gemini: {
    name: 'Gemini CLI',
    settingsDir: '.gemini',
    settingsFile: 'settings.json',
    hookEvent: 'BeforeAgent',
    restartMessage: 'Restart Gemini CLI to activate the hook.',
  },
};

// Format pinned files content for static exports
async function formatPinnedContent(config: CtxPilotConfig, projectRoot: string, maxChars?: number): Promise<string> {
  const sections: string[] = [];
  let totalChars = 0;

  for (const pinnedPath of config.pinned) {
    try {
      const absolutePath = join(projectRoot, pinnedPath);
      let content = await readFile(absolutePath, 'utf-8');

      // Truncate if needed
      if (maxChars && totalChars + content.length > maxChars) {
        const remaining = maxChars - totalChars - 100; // Leave room for header
        if (remaining > 200) {
          content = content.slice(0, remaining) + '\n\n... (truncated)';
        } else {
          break;
        }
      }

      sections.push(`## ${pinnedPath}\n\n${content}`);
      totalChars += content.length;

      if (maxChars && totalChars >= maxChars) break;
    } catch {
      // Skip missing files
    }
  }

  return sections.join('\n\n---\n\n');
}

// Format index summary for static exports
function formatIndexSummary(index: ProjectIndex): string {
  const lines: string[] = ['## Codebase Structure\n'];

  for (const file of index.files.slice(0, 50)) { // Limit to 50 files
    lines.push(`### ${file.path}`);
    for (const section of file.sections.slice(0, 10)) { // Limit sections per file
      lines.push(`- ${section.title} (lines ${section.lineStart}-${section.lineEnd})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

const EXPORT_CONFIGS: Record<ExportTarget, ExportConfig> = {
  cursor: {
    name: 'Cursor',
    outputPath: '.cursorrules',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --cursor

${pinned}

---

${summary}
`;
    },
  },
  windsurf: {
    name: 'Windsurf',
    outputPath: '.windsurfrules',
    maxChars: 6000,
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot, 4000);
      const stats = getIndexStats(index);

      return `# Project Context (generated by ctx-pilot)
# Regenerate with: npx ctx-pilot export --windsurf

${pinned}

---

## Project Stats
- Indexed files: ${stats.files}
- Indexed sections: ${stats.sections}
- Pinned files: ${config.pinned.join(', ') || 'none'}
`;
    },
  },
  aider: {
    name: 'Aider',
    outputPath: '.aider.context.md',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);
      const summary = formatIndexSummary(index);

      return `# Project Context for Aider
# Use with: aider --read .aider.context.md
# Regenerate with: npx ctx-pilot export --aider

${pinned}

---

${summary}
`;
    },
  },
  mdc: {
    name: 'Cursor MDC',
    outputPath: '.cursor/rules/ctx-pilot.mdc',
    format: async (config, index, projectRoot) => {
      const pinned = await formatPinnedContent(config, projectRoot);

      return `---
description: Project context from ctx-pilot
globs: ["**/*"]
alwaysApply: true
---

# Project Context

${pinned}

## Key Files

${config.pinned.map(f => `- ${f}`).join('\n')}
`;
    },
  },
};

const OPTIMIZE_PROMPT = `# Build ctx-pilot Index

Analyze this codebase and build an optimized index for ctx-pilot.

## Your Task

1. **Review the codebase structure** - identify source files, documentation, tests, and config files

2. **Update \`.context/config.json\`** with appropriate patterns:
   \`\`\`json
   {
     "pinned": ["<core docs that are always relevant>"],
     "include": ["<glob patterns for files to index>"],
     "exclude": ["node_modules/**", "dist/**", "<other build artifacts>"],
     "excludeFromSuggestions": ["tests/**"],
     "domainStopwords": ["<common project terms to ignore>"]
   }
   \`\`\`

   - \`excludeFromSuggestions\`: Files to index but never suggest (e.g., tests for completeness)
   - \`domainStopwords\`: Terms that appear everywhere and aren't useful for search

3. **Build \`.context/index.json\`** by analyzing included files:
   \`\`\`json
   {
     "version": "1.1.0",
     "lastUpdated": "<ISO timestamp>",
     "files": [{
       "path": "<relative path>",
       "sections": [{
         "title": "<descriptive title>",
         "lineStart": 1,
         "lineEnd": 50,
         "preview": "<what this section does, not just code>",
         "keywords": ["<synonyms and related terms>"]
       }]
     }]
   }
   \`\`\`

4. **Verify** your index:
   - \`npx ctx-pilot validate\` - Check for errors
   - \`npx ctx-pilot search "authentication"\` - Test what matches a query

## CRITICAL: Add Synonyms to Keywords

The search only finds exact keyword matches. Users might search "login" but your code calls it "authenticate". **You must add synonyms.**

For each section, ask: "What words might someone use to search for this?"

| If the code says... | Also add keywords... |
|---------------------|----------------------|
| authenticate, auth | login, signin, logon, credential, session |
| config, configuration | settings, options, preferences, setup |
| error, exception | failure, throw, catch, fault, problem |
| create | add, new, insert, make, build, generate |
| delete | remove, destroy, drop, erase, clear |
| update | edit, modify, change, patch, set |
| user | account, profile, member, identity, person |
| fetch, request | get, load, retrieve, query, call, api |
| save | store, persist, write, cache |
| validate | check, verify, ensure, assert, test |

## Good vs Bad Examples

**Good:**
\`\`\`json
{
  "title": "Authentication Middleware",
  "preview": "Validates JWT tokens and attaches user to request context",
  "keywords": ["auth", "authenticate", "login", "signin", "jwt", "token", "session", "credential", "verify"]
}
\`\`\`

**Bad:**
\`\`\`json
{
  "title": "function authenticateUser",
  "preview": "export async function authenticateUser(req, res, next) {",
  "keywords": ["authenticateuser"]
}
\`\`\`

The good example will match searches for "login", "auth", "session", "jwt", etc. The bad example only matches "authenticateuser".
`;

const SETUP_INSTRUCTIONS = `Run \`npx ctx-pilot init\` to set up.`;

async function readStdin(): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf-8');
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function writeOptimizePrompt(projectRoot: string): Promise<void> {
  const promptPath = join(projectRoot, '.context', 'optimize.md');
  await writeFile(promptPath, OPTIMIZE_PROMPT, 'utf-8');
}

async function detectEnvironment(projectRoot: string): Promise<Environment> {
  const claudeExists = await pathExists(join(projectRoot, '.claude'));
  const geminiExists = await pathExists(join(projectRoot, '.gemini'));

  if (claudeExists && geminiExists) {
    const claudeSettings = await pathExists(join(projectRoot, '.claude', 'settings.json'));
    const geminiSettings = await pathExists(join(projectRoot, '.gemini', 'settings.json'));
    if (claudeSettings && !geminiSettings) return 'claude';
    if (geminiSettings && !claudeSettings) return 'gemini';
    return 'claude';
  }

  if (claudeExists) return 'claude';
  if (geminiExists) return 'gemini';

  if (process.env.CLAUDE_CODE || process.env.ANTHROPIC_API_KEY) return 'claude';
  if (process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY) return 'gemini';

  return 'claude';
}

async function installHook(projectRoot: string, forceEnv?: Environment): Promise<void> {
  const env = forceEnv || await detectEnvironment(projectRoot);

  if (env === 'unknown') {
    console.log('Could not detect AI CLI environment.');
    console.log('Use --claude or --gemini flag to specify.');
    return;
  }

  const config = ENVIRONMENTS[env];
  const settingsDir = join(projectRoot, config.settingsDir);
  const settingsPath = join(settingsDir, config.settingsFile);

  await mkdir(settingsDir, { recursive: true });

  let settings: Record<string, unknown> = {};
  try {
    const content = await readFile(settingsPath, 'utf-8');
    settings = JSON.parse(content);
  } catch {
    // File doesn't exist
  }

  if (!settings.hooks) settings.hooks = {};
  const hooks = settings.hooks as Record<string, unknown[]>;
  if (!hooks[config.hookEvent]) hooks[config.hookEvent] = [];

  const eventHooks = hooks[config.hookEvent] as Array<Record<string, unknown>>;
  const hasHook = eventHooks.some((h) => {
    const hHooks = h.hooks as Array<Record<string, unknown>> | undefined;
    return hHooks?.some((hh) => String(hh.command || '').includes('ctx-pilot'));
  });

  if (hasHook) {
    console.log(`Hook already installed for ${config.name}.`);
    return;
  }

  eventHooks.push({
    matcher: '',
    hooks: [{ type: 'command', command: 'npx ctx-pilot' }],
  });

  await writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf-8');
  console.log(`Hook installed for ${config.name} at ${config.settingsDir}/${config.settingsFile}`);
}

async function runExport(projectRoot: string, target: ExportTarget): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);
  if (!index) {
    console.error('No index found. Ask your AI to: "Follow the instructions in .context/optimize.md"');
    process.exit(1);
  }

  const exportConfig = EXPORT_CONFIGS[target];
  const outputPath = join(projectRoot, exportConfig.outputPath);

  // Ensure directory exists for MDC
  await mkdir(dirname(outputPath), { recursive: true });

  const content = await exportConfig.format(config, index, projectRoot);
  await writeFile(outputPath, content, 'utf-8');

  console.log(`Exported to ${exportConfig.outputPath} for ${exportConfig.name}`);
}

async function runInit(projectRoot: string, forceEnv?: Environment): Promise<void> {
  const env = forceEnv || await detectEnvironment(projectRoot);
  const envConfig = env !== 'unknown' ? ENVIRONMENTS[env] : null;

  if (await configExists(projectRoot)) {
    console.log('Already configured. See .context/config.json');
    return;
  }

  const config = getDefaultConfig();
  await saveConfig(projectRoot, config);
  await writeOptimizePrompt(projectRoot);

  console.log('Created .context/config.json');
  console.log('Created .context/optimize.md');

  if (envConfig) {
    console.log(`\nDetected ${envConfig.name}. Installing hook...`);
    await installHook(projectRoot, env as Exclude<Environment, 'unknown'>);
    console.log(`\nSetup complete! ${envConfig.restartMessage}`);
  } else {
    console.log('\nCould not detect AI CLI environment.');
    console.log('Run `npx ctx-pilot hook --claude` or `npx ctx-pilot hook --gemini` to install.');
  }

  console.log('\nTo build the index, ask your AI to:');
  console.log('  "Follow the instructions in .context/optimize.md"');
}

async function runStatus(projectRoot: string): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.log('Status: Not configured');
    console.log('Run `npx ctx-pilot init` to set up.');
    return;
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);
  const env = await detectEnvironment(projectRoot);

  console.log('Status: Configured');
  console.log(`Environment: ${env !== 'unknown' ? ENVIRONMENTS[env].name : 'Unknown'}`);
  console.log(`\nConfig (.context/config.json):`);
  console.log(`  Pinned: ${config.pinned.length > 0 ? config.pinned.join(', ') : '(none)'}`);
  console.log(`  Include: ${config.include.join(', ')}`);
  console.log(`  Exclude: ${config.exclude.length > 0 ? config.exclude.join(', ') : '(none)'}`);

  if (index) {
    const stats = getIndexStats(index);
    console.log(`\nIndex (.context/index.json):`);
    console.log(`  Files: ${stats.files}`);
    console.log(`  Sections: ${stats.sections}`);
    console.log(`  Keywords: ${stats.totalKeywords.toLocaleString()} total, ${stats.uniqueKeywords.toLocaleString()} unique`);
    console.log(`  Avg sections/file: ${stats.avgSectionsPerFile}`);
    if (stats.emptyFiles > 0) {
      console.log(`  Empty files: ${stats.emptyFiles}`);
    }
    console.log(`  Last updated: ${index.lastUpdated}`);
  } else {
    console.log(`\nIndex: Not built yet.`);
  }

  // Check hooks
  console.log(`\nHooks:`);
  for (const [, envConfig] of Object.entries(ENVIRONMENTS)) {
    const settingsPath = join(projectRoot, envConfig.settingsDir, envConfig.settingsFile);
    if (await pathExists(settingsPath)) {
      try {
        const content = await readFile(settingsPath, 'utf-8');
        const settings = JSON.parse(content);
        const hooks = settings.hooks?.[envConfig.hookEvent] || [];
        const hasHook = hooks.some((h: Record<string, unknown>) => {
          const hHooks = h.hooks as Array<Record<string, unknown>> | undefined;
          return hHooks?.some((hh) => String(hh.command || '').includes('ctx-pilot'));
        });
        console.log(`  ${envConfig.name}: ${hasHook ? 'Installed' : 'Not installed'}`);
      } catch {
        console.log(`  ${envConfig.name}: Error reading settings`);
      }
    }
  }

  // Check exports
  console.log(`\nExports:`);
  for (const [, exportConfig] of Object.entries(EXPORT_CONFIGS)) {
    const exists = await pathExists(join(projectRoot, exportConfig.outputPath));
    if (exists) {
      console.log(`  ${exportConfig.name}: ${exportConfig.outputPath}`);
    }
  }
}

async function runAutoIndex(projectRoot: string, options: { verbose?: boolean; force?: boolean }): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const existingIndex = await loadIndex(projectRoot);

  console.log('Building auto-index...');
  if (options.verbose) {
    console.log('');
  }

  const index = await buildAutoIndex(projectRoot, config, { verbose: options.verbose, force: options.force }, existingIndex);
  await saveIndex(projectRoot, index);

  const stats = getIndexStats(index);
  console.log(`\nAuto-index complete!`);
  console.log(`  Files: ${stats.files}`);
  console.log(`  Sections: ${stats.sections}`);
  console.log(`\nTip: AI can enhance this index with better keywords and previews.`);
  console.log(`Run \`npx ctx-pilot validate\` to check for issues.`);
}

async function runValidate(projectRoot: string): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);

  if (!index) {
    console.error('No index found. Run `npx ctx-pilot auto-index` first.');
    process.exit(1);
  }

  console.log('Validating index...\n');
  const result = await validateIndex(projectRoot, config, index);
  console.log(formatValidationResult(result));

  if (!result.valid) {
    process.exit(1);
  }
}

async function runSearch(projectRoot: string, query: string): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);
  const index = await loadIndex(projectRoot);

  if (!index) {
    console.error('No index found. Run `npx ctx-pilot auto-index` first.');
    process.exit(1);
  }

  const topics = extractTopics(query);
  console.log(`Topics extracted: ${topics.length > 0 ? topics.join(', ') : '(none)'}`);

  if (topics.length === 0) {
    console.log('\nNo searchable topics found in query.');
    return;
  }

  const results = searchSections(index, topics.join(' '), { maxResults: 20 });

  if (results.length === 0) {
    console.log('\nNo matches found.');
    return;
  }

  const minScore = config.minScore ?? 1.0;
  console.log(`\nResults (${results.length} matches, threshold: ${minScore}):\n`);

  for (const r of results) {
    const marker = r.score >= minScore ? '✓' : '✗';
    console.log(`${marker} [${r.score.toFixed(2)}] ${r.file}:${r.section.lineStart} - ${r.section.title}`);
    console.log(`  Keywords: ${r.section.keywords.slice(0, 5).join(', ')}`);
  }

  const passing = results.filter((r) => r.score >= minScore).length;
  console.log(`\n${passing} of ${results.length} results pass threshold.`);
}

async function runWatch(projectRoot: string): Promise<void> {
  if (!(await configExists(projectRoot))) {
    console.error('Not configured. Run `npx ctx-pilot init` first.');
    process.exit(1);
  }

  const config = await loadConfig(projectRoot);

  console.log('Watching for file changes... (Ctrl+C to stop)\n');

  let debounceTimer: ReturnType<typeof setTimeout> | null = null;
  let isRebuilding = false;

  const rebuild = async () => {
    if (isRebuilding) return;
    isRebuilding = true;

    try {
      const existingIndex = await loadIndex(projectRoot);
      const index = await buildAutoIndex(projectRoot, config, {}, existingIndex);
      await saveIndex(projectRoot, index);
      const stats = getIndexStats(index);
      console.log(`[${new Date().toLocaleTimeString()}] Rebuilt: ${stats.files} files, ${stats.sections} sections`);
    } catch (error) {
      console.error(`[${new Date().toLocaleTimeString()}] Error:`, (error as Error).message);
    } finally {
      isRebuilding = false;
    }
  };

  // Get directories to watch from include patterns
  const dirsToWatch = new Set<string>();
  for (const pattern of config.include) {
    // Extract the base directory from the pattern
    const parts = pattern.split('/');
    if (parts[0] === '**') {
      dirsToWatch.add('.');
    } else if (parts[0] && !parts[0].includes('*')) {
      dirsToWatch.add(parts[0]);
    } else {
      dirsToWatch.add('.');
    }
  }

  // Set up watchers
  for (const dir of dirsToWatch) {
    const watchPath = join(projectRoot, dir);
    try {
      watch(watchPath, { recursive: true }, () => {
        if (debounceTimer) clearTimeout(debounceTimer);
        debounceTimer = setTimeout(rebuild, 500);
      });
      console.log(`Watching: ${dir === '.' ? projectRoot : watchPath}`);
    } catch {
      // Directory might not exist, skip silently
    }
  }

  console.log('');

  // Keep process alive
  await new Promise(() => {});
}

async function getStaleFiles(projectRoot: string, index: ProjectIndex): Promise<Set<string>> {
  const stale = new Set<string>();
  const indexDate = new Date(index.lastUpdated);

  for (const file of index.files) {
    try {
      const fileStat = await stat(join(projectRoot, file.path));
      if (fileStat.mtime > indexDate) {
        stale.add(file.path);
      }
    } catch {
      // File deleted or inaccessible = stale
      stale.add(file.path);
    }
  }

  return stale;
}

function formatSuggestions(
  pinnedFiles: string[],
  results: ScoredSection[],
  staleFiles: Set<string>,
  maxSuggestions = 5
): { text: string; hasStale: boolean } {
  const lines: string[] = [];
  let hasStale = false;

  if (pinnedFiles.length > 0) {
    lines.push('**Pinned (always relevant):**');
    for (const file of pinnedFiles) {
      lines.push(`- ${file}`);
    }
    lines.push('');
  }

  if (results.length > 0) {
    lines.push('**Relevant to your task:**');
    const top = results.slice(0, maxSuggestions);
    for (const r of top) {
      const lineRange = `lines ${r.section.lineStart}-${r.section.lineEnd}`;
      const staleMarker = staleFiles.has(r.file) ? ' ⚠️' : '';
      if (staleFiles.has(r.file)) hasStale = true;
      lines.push(`- ${r.file} (${lineRange}) - ${r.section.title}${staleMarker}`);
    }
  }

  return { text: lines.join('\n'), hasStale };
}

async function runHook(): Promise<void> {
  const projectRoot = process.cwd();

  try {
    const input = await readStdin();
    if (!input.trim()) process.exit(0);

    let data: HookInput;
    try {
      data = JSON.parse(input);
    } catch {
      process.exit(0);
    }

    if (!(await configExists(projectRoot))) {
      console.log(SETUP_INSTRUCTIONS);
      process.exit(0);
    }

    const config = await loadConfig(projectRoot);

    // Set domain-specific stopwords if configured
    if (config.domainStopwords && config.domainStopwords.length > 0) {
      setDomainStopwords(config.domainStopwords);
    }

    const index = await loadIndex(projectRoot);
    if (!index) {
      console.log(`<ctx-pilot>
No index found. Ask your AI to: "Follow the instructions in .context/optimize.md"
</ctx-pilot>`);
      process.exit(0);
    }

    const topics = extractTopics(data.prompt);
    const hasPinned = config.pinned.length > 0;

    // Smart skip: configurable thresholds
    const minTopics = config.minTopics ?? 2;
    const minScore = config.minScore ?? 1.0;

    // Smart skip: if fewer than minTopics and no pinned files, stay silent
    if (topics.length < minTopics && !hasPinned) {
      process.exit(0);
    }

    const query = topics.join(' ');
    const results = query ? searchSections(index, query, { maxResults: 10 }) : [];

    // Smart skip: if no results score above threshold and no pinned files, stay silent
    const hasRelevantResults = results.some((r) => r.score >= minScore);
    if (!hasRelevantResults && !hasPinned) {
      process.exit(0);
    }

    // Filter results to only include those above threshold
    let relevantResults = results.filter((r) => r.score >= minScore);

    // Filter out excludeFromSuggestions patterns
    if (config.excludeFromSuggestions && config.excludeFromSuggestions.length > 0) {
      const excludePatterns = config.excludeFromSuggestions;
      relevantResults = relevantResults.filter((r) => {
        return !excludePatterns.some((pattern) => {
          // Simple glob matching: ** matches anything, * matches non-slash
          const regex = new RegExp(
            '^' + pattern.replace(/\*\*/g, '.*').replace(/\*/g, '[^/]*') + '$'
          );
          return regex.test(r.file);
        });
      });
    }

    // Check for stale files
    const staleFiles = await getStaleFiles(projectRoot, index);
    const { text: suggestions, hasStale } = formatSuggestions(config.pinned, relevantResults, staleFiles);

    if (suggestions) {
      const staleNote = hasStale
        ? '\n\n⚠️ Before answering, update .context/index.json for files marked ⚠️.'
        : '';

      console.log(`<ctx-pilot>
Look into these files for context:

${suggestions}${staleNote}
</ctx-pilot>`);
    }

    process.exit(0);
  } catch (error) {
    console.error('ctx-pilot error:', error);
    process.exit(0);
  }
}

function printHelp(): void {
  console.log(`ctx-pilot - Intelligent context management for AI coding assistants

Supported:
  Dynamic hooks: Claude Code, Gemini CLI
  Static exports: Cursor, Windsurf, Aider

Usage:
  npx ctx-pilot                Run as hook (reads from stdin)
  npx ctx-pilot init           Create config and install hook
  npx ctx-pilot status         Show config, index, and hook status
  npx ctx-pilot auto-index     Build index from source files
  npx ctx-pilot validate       Check index for issues
  npx ctx-pilot search <query> Test what matches a query
  npx ctx-pilot watch          Auto-rebuild on file changes

Hooks (dynamic, per-prompt):
  npx ctx-pilot hook           Install hook (auto-detects Claude/Gemini)
  npx ctx-pilot hook --claude  Install for Claude Code
  npx ctx-pilot hook --gemini  Install for Gemini CLI

Exports (static files):
  npx ctx-pilot export --cursor    Generate .cursorrules
  npx ctx-pilot export --windsurf  Generate .windsurfrules
  npx ctx-pilot export --aider     Generate .aider.context.md
  npx ctx-pilot export --mdc       Generate .cursor/rules/ctx-pilot.mdc

Options:
  --verbose, -v    Show detailed output (for auto-index)
  --force, -f      Force full rebuild (ignore cache)

Config file: .context/config.json
Index file:  .context/index.json
`);
}

function parseEnvFlag(args: string[]): Environment | undefined {
  if (args.includes('--claude')) return 'claude';
  if (args.includes('--gemini')) return 'gemini';
  return undefined;
}

function parseExportTargets(args: string[]): ExportTarget[] {
  const targets: ExportTarget[] = [];
  if (args.includes('--cursor')) targets.push('cursor');
  if (args.includes('--windsurf')) targets.push('windsurf');
  if (args.includes('--aider')) targets.push('aider');
  if (args.includes('--mdc')) targets.push('mdc');
  if (args.includes('--all')) {
    return ['cursor', 'windsurf', 'aider', 'mdc'];
  }
  return targets;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const projectRoot = process.cwd();
  const forceEnv = parseEnvFlag(args);
  const exportTargets = parseExportTargets(args);

  switch (args[0]) {
    case 'init':
      await runInit(projectRoot, forceEnv);
      break;
    case 'status':
      await runStatus(projectRoot);
      break;
    case 'auto-index':
    case 'index':
      await runAutoIndex(projectRoot, {
        verbose: args.includes('--verbose') || args.includes('-v'),
        force: args.includes('--force') || args.includes('-f'),
      });
      break;
    case 'validate':
      await runValidate(projectRoot);
      break;
    case 'search': {
      const searchQuery = args.slice(1).join(' ');
      if (!searchQuery) {
        console.error('Usage: ctx-pilot search <query>');
        process.exit(1);
      }
      await runSearch(projectRoot, searchQuery);
      break;
    }
    case 'watch':
      await runWatch(projectRoot);
      break;
    case 'hook':
    case 'install':
    case 'install-hook':
      await installHook(projectRoot, forceEnv);
      break;
    case 'export':
      if (exportTargets.length === 0) {
        console.error('Specify export target: --cursor, --windsurf, --aider, --mdc, or --all');
        process.exit(1);
      }
      for (const target of exportTargets) {
        await runExport(projectRoot, target);
      }
      break;
    case 'help':
    case '--help':
    case '-h':
      printHelp();
      break;
    default:
      await runHook();
  }
}

main().catch((error) => {
  console.error('Error:', error.message);
  process.exit(1);
});
